### PR TITLE
Feature/add bq

### PR DESCRIPTION
**Pull request by haitiangk92**

### CODE REVIEW

**Review by mourtallah — APPROVED** [review]

**Review by mparayil — APPROVED** [review]

**Comment by haitiangk92** [comment]
The new changes have been tested in the following dag:https://dev-gdo-analytics.airflow.colpal.cloud/code?dag_id=bq_sf_sync_ColgateTuHogarLATAM_Final&root=

The container using the new bq protocol is the bq_to_gcs_v4 container. Note the use of the new bq module and also the use of the new secrets protocol. There is a new class in the cla module that turns the input dictionary of secret locations into an object allowing the dev to select the specific type of secret by accessing the attributes of the secrets object.

image
image

Use in the dag is as follows:
image

**Review by mourtallah — APPROVED** [review]
beautiful work Manny, much needed too. 💯

**Review by mparayil — APPROVED** [review]
+1  Mourtallah's comment 👍

**Review by KevinDukelow5 — DISMISSED** [review]
Looks good, good testing

**Comment by haitiangk92** [comment]
For unpinned versions that will be affected by these changes, an error code will appear to point to the updated README file

image

**Review by mourtallah — APPROVED** [review]

**Comment by haitiangk92** [comment]
Also, reworked the testing container to further utilize the new functionality
image

**Review by mparayil — APPROVED** [review]

**Pull request merged**
